export type Locale = "zh" | "en";
export const LOCALE_COOKIE = "locale";

export const DICT = {
  zh: {
    "nav.home": "首页",
    "nav.hot": "热门推荐",
    "nav.categories": "分类浏览",
    "nav.publish": "我要发布",
    "nav.login": "注册登录",
    "nav.logout": "退出登录",
    "nav.admin": "管理后台",
    "nav.memberCenter": "会员中心",
    "nav.lang": "语言",
    "search.placeholder": "搜索提示词：电影感 / 赛博朋克 / 产品广告…",
    "search.button": "搜索",
    "cat.all": "全部",
    "cat.browse": "浏览分类",
    "cat.count": "{n} 个提示词",
    "cat.badge": "分类浏览",
    "cat.heroTitle": "探索提示词分类",
    "cat.heroSub": "{n} 大分类，满足你的各种 AI 创作需求",
    "type.all": "全部类型",
    "type.video": "文生视频",
    "type.image": "文生图",
    "type.audio": "文生音频",
    "type.text": "文本创作",
    "sort.new": "最新",
    "sort.likes": "按点赞热门",
    "sort.views": "按浏览量",
    "sort.relevance": "相关度",
    "home.featured": "发现无限创意",
    "home.featuredSub": "探索来自全球各地AI大模型多种语言的全面完整项目提示词，让您思如泉涌创造无限可能",
    "home.viewAll": "查看全部",
    "hot.title": "热门推荐",
    "hot.sub": "全站最受欢迎的提示词，按点赞数排序",
    "catlist.back": "← 分类浏览",
    "member.title": "会员中心",
    "member.myPosts": "我的发布",
    "member.myFavs": "我的收藏",
    "member.likesGot": "获赞",
    "member.memberSince": "注册时间",
    "member.tier": "会员等级",
    "member.free": "普通会员",
    "member.noPosts": "还没有发布过提示词",
    "member.noFavs": "还没有收藏内容",
    "member.goPublish": "去发布一条 →",
    "total.count": "共 {n} 个作品",
    "card.prompts": "{n} 条",
    "card.community": "社区用户",
    "detail.views": "{n} 浏览",
    "detail.original": "提示词原文",
    "detail.originalWork": "原作品 ↗",
    "detail.related": "相关推荐",
    "detail.translating": "自动翻译中…",
    "detail.translateFail": "翻译暂时不可用，请稍后重试",
    "detail.translateRetry": "重试翻译",
    "detail.pending": "审核中",
    "detail.rejected": "未通过",
    "detail.rejectReason": "驳回原因",
    "detail.membership": "会员",
    "btn.copy": "复制",
    "btn.copied": "已复制 ✓",
    "btn.like": "点赞",
    "btn.favorite": "收藏",
    "btn.favorited": "★ 已收藏",
    "search.title": "搜索",
    "search.results": "{n} 条结果",
    "search.empty": "输入关键词开始搜索",
    "search.noresult": "没有找到相关内容",
    "search.engineDown": "搜索引擎暂时不可用：{msg}",
    "common.prev": "上一页",
    "common.next": "下一页",
    "publish.title": "发布提示词",
    "publish.field.title": "标题 *",
    "publish.field.type": "类型",
    "publish.field.category": "分类",
    "publish.field.model": "模型（可选）",
    "publish.field.sourceUrl": "原作品链接（可选，转载出处）",
    "publish.field.tags": "标签（逗号分隔，最多 8 个）",
    "publish.field.desc": "简介（可选）",
    "publish.field.content": "提示词内容 *（支持富文本，可插入图片/视频）",
    "publish.field.media": "封面图",
    "publish.cover": "封面图（不上传将自动从内容中提取第一张图片）",
    "publish.autoTags": "自动获取标签",
    "publish.autoDesc": "自动获取简介",
    "publish.autoGetting": "获取中…",
    "publish.upload": "上传本地文件",
    "publish.dropzone": "点击选择，或把文件拖到这里（支持一次多选）",
    "publish.dropzoneSingle": "点击选择或拖拽图片",
    "publish.retry": "重试",
    "publish.dropReject": "已跳过：类型不支持或超过大小限制",
    "publish.clearDone": "清空记录",
    "publish.embed": "或粘贴图片/视频链接（支持 YouTube / Bilibili / 直链，转载）",
    "publish.addLink": "添加",
    "publish.remove": "移除",
    "publish.uploading": "上传中…",
    "publish.uploadOk": "上传成功",
    "publish.uploadFail": "上传失败：{msg}",
    "publish.embedFail": "无法识别该链接，请粘贴图片/视频直链或 YouTube/Bilibili 链接",
    "publish.submit": "发布",
    "publish.submitting": "发布中…",
    "publish.pendingTip": "当前站点开启发布审核，提交后将在后台审核通过后公开。",
    "publish.donePending": "已提交，等待管理员审核",
    "publish.myPosts": "我的发布",
    "auth.username": "用户名",
    "auth.password": "密码",
    "auth.email": "邮箱",
    "auth.login": "登录",
    "auth.register": "注册",
    "auth.loginTitle": "登录 完整提示词",
    "auth.registerTitle": "注册 完整提示词",
    "auth.noAccount": "没有账号？去注册",
    "auth.hasAccount": "已有账号？去登录",
    "auth.registrationClosed": "本站已关闭注册，请联系管理员",
    "admin.title": "管理后台",
    "admin.dashboard": "仪表盘",
    "admin.prompts": "提示词管理",
    "admin.users": "用户管理",
    "admin.basic": "基本设置",
    "admin.publishSettings": "发布设置",
    "admin.membership": "会员设置",
    "admin.save": "保存设置",
    "admin.saved": "已保存 ✓",
  },
  en: {
    "nav.home": "Home",
    "nav.hot": "Popular",
    "nav.categories": "Categories",
    "nav.publish": "Publish",
    "nav.login": "Sign in / Up",
    "nav.logout": "Log out",
    "nav.admin": "Admin",
    "nav.memberCenter": "Member center",
    "nav.lang": "Language",
    "search.placeholder": "Search prompts: cinematic, cyberpunk, product ad…",
    "search.button": "Search",
    "cat.all": "All",
    "cat.browse": "Browse",
    "cat.count": "{n} prompts",
    "cat.badge": "CATEGORIES",
    "cat.heroTitle": "Explore prompt categories",
    "cat.heroSub": "{n} categories for all your AI creation needs",
    "type.all": "All types",
    "type.video": "Video",
    "type.image": "Image",
    "type.audio": "Audio",
    "type.text": "Text",
    "sort.new": "Newest",
    "sort.likes": "Top liked",
    "sort.views": "Most viewed",
    "sort.relevance": "Relevance",
    "home.featured": "Discover Infinite Creativity",
    "home.featuredSub": "Explore comprehensive, complete project prompts for AI models in multiple languages from around the world — spark your inspiration and create endless possibilities",
    "home.viewAll": "View all",
    "hot.title": "Popular",
    "hot.sub": "The most-loved prompts across the community",
    "catlist.back": "← All categories",
    "member.title": "Member center",
    "member.myPosts": "My posts",
    "member.myFavs": "My favorites",
    "member.likesGot": "Likes received",
    "member.memberSince": "Member since",
    "member.tier": "Membership",
    "member.free": "Free",
    "member.noPosts": "You haven't published anything yet",
    "member.noFavs": "No favorites yet",
    "member.goPublish": "Publish one →",
    "total.count": "{n} prompts",
    "card.prompts": "{n}",
    "card.community": "Community",
    "detail.views": "{n} views",
    "detail.original": "Original prompt",
    "detail.originalWork": "Original work ↗",
    "detail.related": "Related",
    "detail.translating": "Auto-translating…",
    "detail.translateFail": "Translation unavailable, please retry later",
    "detail.translateRetry": "Retry translation",
    "detail.pending": "Pending review",
    "detail.rejected": "Rejected",
    "detail.rejectReason": "Reason",
    "detail.membership": "Member",
    "btn.copy": "Copy",
    "btn.copied": "Copied ✓",
    "btn.like": "Like",
    "btn.favorite": "Save",
    "btn.favorited": "★ Saved",
    "search.title": "Search",
    "search.results": "{n} results",
    "search.empty": "Type a keyword to search",
    "search.noresult": "No results found",
    "search.engineDown": "Search engine unavailable: {msg}",
    "common.prev": "Prev",
    "common.next": "Next",
    "publish.title": "Publish a prompt",
    "publish.field.title": "Title *",
    "publish.field.type": "Type",
    "publish.field.category": "Category",
    "publish.field.model": "Model (optional)",
    "publish.field.sourceUrl": "Original work URL (optional, source link)",
    "publish.field.tags": "Tags (comma separated, up to 8)",
    "publish.field.desc": "Description (optional)",
    "publish.field.content": "Prompt content * (rich text, images/videos supported)",
    "publish.field.media": "Cover image",
    "publish.cover": "Cover image (auto-extracted from content if not uploaded)",
    "publish.autoTags": "Auto-tag",
    "publish.autoDesc": "Auto description",
    "publish.autoGetting": "Generating…",
    "publish.upload": "Upload local file",
    "publish.dropzone": "Click to choose or drop files here (multi-select)",
    "publish.dropzoneSingle": "Click or drag an image",
    "publish.retry": "Retry",
    "publish.dropReject": "Skipped: unsupported type or too large",
    "publish.clearDone": "Clear list",
    "publish.embed": "or paste an image/video URL (YouTube / Bilibili / direct link)",
    "publish.addLink": "Add",
    "publish.remove": "Remove",
    "publish.uploading": "Uploading…",
    "publish.uploadOk": "Uploaded",
    "publish.uploadFail": "Upload failed: {msg}",
    "publish.embedFail": "Unrecognized link. Use a direct media URL or a YouTube/Bilibili link",
    "publish.submit": "Publish",
    "publish.submitting": "Publishing…",
    "publish.pendingTip": "Review mode is on: your post will be public after an admin approves it.",
    "publish.donePending": "Submitted, waiting for review",
    "publish.myPosts": "My posts",
    "auth.username": "Username",
    "auth.password": "Password",
    "auth.email": "Email",
    "auth.login": "Sign in",
    "auth.register": "Sign up",
    "auth.loginTitle": "Sign in to CompletePrompt",
    "auth.registerTitle": "Create your CompletePrompt account",
    "auth.noAccount": "No account? Sign up",
    "auth.hasAccount": "Already have an account? Sign in",
    "auth.registrationClosed": "Registration is closed. Please contact the administrator.",
    "admin.title": "Admin",
    "admin.dashboard": "Dashboard",
    "admin.prompts": "Prompts",
    "admin.users": "Users",
    "admin.basic": "General",
    "admin.publishSettings": "Publishing",
    "admin.membership": "Membership",
    "admin.save": "Save",
    "admin.saved": "Saved ✓",
  },
} as const;

export type DictKey = keyof (typeof DICT)["zh"];

export function translate(locale: Locale, key: DictKey, vars?: Record<string, string | number>): string {
  let s = (DICT[locale] as Record<string, string>)[key] ?? (DICT.zh as Record<string, string>)[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v));
  return s;
}
